name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Python 3.12 einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Abhängigkeiten installieren
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Tests ausführen
        run: |
          echo "Hier kommen deine Testbefehle rein, z.B. pytest"
          # pytest tests/

      - name: Docker Image bauen
        run: docker build -t invoiceinsight .

      # Optional: Push zu Docker Hub (nur wenn du das willst)
      # - name: Docker Login
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Docker Image pushen
      #   run: docker push invoiceinsight
